-- PostgreSQL Schema for your application

CREATE TABLE IF NOT EXISTS "User" (
    "id" SERIAL PRIMARY KEY,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "passwordHash" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "kycStatus" VARCHAR(50) NOT NULL DEFAULT 'UNVERIFIED',
    "stripeCustomerId" VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS "ChatMessage" (
    "id" SERIAL PRIMARY KEY,
    "userId" INTEGER,
    "guestId" VARCHAR(255),
    "sender" VARCHAR(50) NOT NULL,
    "content" TEXT NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Swap" (
    "id" SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL,
    "fromCoin" VARCHAR(50) NOT NULL,
    "toCoin" VARCHAR(50) NOT NULL,
    "fromAmount" DOUBLE PRECISION NOT NULL,
    "toAmount" DOUBLE PRECISION NOT NULL,
    "rate" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Position" (
    "id" SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL,
    "symbol" VARCHAR(50) NOT NULL DEFAULT 'BTCUSDT',
    "side" VARCHAR(10) NOT NULL,
    "type" VARCHAR(20) NOT NULL DEFAULT 'MARKET',
    "marginMode" VARCHAR(20) NOT NULL DEFAULT 'CROSS',
    "entryPrice" DOUBLE PRECISION NOT NULL,
    "size" DOUBLE PRECISION NOT NULL,
    "marginUsed" DOUBLE PRECISION NOT NULL,
    "leverage" INTEGER NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Wallet" (
    "id" SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL,
    "coin" VARCHAR(50) NOT NULL,
    "network" VARCHAR(50) NOT NULL,
    "address" VARCHAR(255) NOT NULL UNIQUE,
    "derivationIndex" INTEGER NOT NULL,
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    UNIQUE("userId", "coin", "network")
);

CREATE TABLE IF NOT EXISTS "Balance" (
    "id" SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL,
    "coin" VARCHAR(50) NOT NULL,
    "available" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "locked" DOUBLE PRECISION NOT NULL DEFAULT 0,
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    UNIQUE("userId", "coin")
);

CREATE TABLE IF NOT EXISTS "Deposit" (
    "id" SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL,
    "txHash" VARCHAR(255) NOT NULL UNIQUE,
    "network" VARCHAR(50) NOT NULL,
    "coin" VARCHAR(50) NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "confirmations" INTEGER NOT NULL DEFAULT 0,
    "status" VARCHAR(50) NOT NULL DEFAULT 'DETECTED',
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Withdrawal" (
    "id" SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL,
    "coin" VARCHAR(50) NOT NULL,
    "network" VARCHAR(50) NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "toAddress" VARCHAR(255) NOT NULL,
    "txHash" VARCHAR(255) UNIQUE,
    "status" VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Transfer" (
    "id" SERIAL PRIMARY KEY,
    "senderId" INTEGER NOT NULL,
    "receiverId" INTEGER NOT NULL,
    "coin" VARCHAR(50) NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "fee" DOUBLE PRECISION NOT NULL,
    "netAmount" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY ("senderId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY ("receiverId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "KycRecord" (
    "id" SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL UNIQUE,
    "firstName" VARCHAR(100) NOT NULL,
    "lastName" VARCHAR(100) NOT NULL,
    "dob" VARCHAR(50) NOT NULL,
    "nationality" VARCHAR(100) NOT NULL,
    "idType" VARCHAR(50) NOT NULL,
    "idFrontPath" VARCHAR(255) NOT NULL,
    "idBackPath" VARCHAR(255) NOT NULL,
    "selfiePath" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Otp" (
    "id" SERIAL PRIMARY KEY,
    "email" VARCHAR(255) NOT NULL,
    "otp" VARCHAR(10) NOT NULL,
    "expiresAt" TIMESTAMP NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "Otp_email_idx" ON "Otp"("email");
